# Generated by Django 3.2.6 on 2021-09-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
