# Generated by Django 3.2.6 on 2021-09-06 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_header',
            field=models.URLField(default='https://images.unsplash.com/photo-1442323794357-25b2ec110967'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
