# Generated by Django 3.2.6 on 2021-09-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210906_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_picture',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_header',
        ),
        migrations.AddField(
            model_name='user',
            name='header',
            field=models.URLField(default='https://images.unsplash.com/photo-1608665488977-b26949036f6e'),
        ),
    ]
