# Generated by Django 3.2.6 on 2021-09-08 23:44

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210906_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AlterField(
            model_name='user',
            name='header',
            field=models.URLField(default=network.models.random_header),
        ),
    ]
